[tools]
python = "3.11"
uv = "latest"
ruff = "latest"

[env]
_.python.venv = { path = ".venv", create = true }

[tasks.test]
description = "Run tests"
run = "uv run --exact --package hfdm pytest ./libs/hfdm/tests/"

# uv sync --package hfdm
# uv run --exact --package hfdm pytest ./libs/hfdm/tests/

[tasks.lint]
description = "Lint the code"
run = "ruff check src/"

